### ISSUE TITLE
User web_view_did_finish_load

### ISSUE THREAD

**Issue by cvpe** [mikaelho/pythonista-misc#1]
Hello
Could it be possible to add these two lines to optionally call an user function when a page did finish load.
I need it, I think, for backward/forward the webview.
Thanks 

  def webview_did_finish_load(self, webview):
    url = webview.eval_js('document.URL')
    if hasattr(webview,'user_webview_did_finish_load'):     # new
      webview.user_webview_did_finish_load(url)                # new

**Comment by mikaelho** [comment]
Is it not possible for you to use the regular `delegate` method of implementing these hooks?

**Comment by cvpe** [comment]
I don't understand your question. As you have set the webview.delegate  in the WebScraper class, I can't also set a delegate, can I?

**Comment by mikaelho** [comment]
Ah, my bad. I thought you were talking about WKWebView, not the scraper. In this case you can subclass the WebScraper (like I do in the example at the bottom of the jswrapper.py), and implement your own hook, including `super().webview_did_finish_load(webview)` somewhere.

**Comment by cvpe** [comment]
Ok thanks

In a near future, I'll try the WkWbView that, I'm sorry 😢, I had forgotten
